Fix/openapi endpoints
aiidateam/aiida-optimade pull request #361
Opened 2022-06-01 10:03 UTC by eimrek

Currently the endpoints 

```
"extensions/docs",
"extensions/redoc",
"extensions/openapi.json",
```

are not available on materialscloud. See e.g. https://aiida.materialscloud.org/optimade-sample/optimade/v1/extensions/docs

(but they are listed on https://aiida.materialscloud.org/optimade-sample/optimade/v1/info)

On localhost, they are available.

The problem seems to stem from here:

https://github.com/aiidateam/aiida-optimade/blob/b48cb39e27ddf1db3e65322412bdd1ecf5b0ee67/aiida_optimade/main.py#L78-L80

Comparing with similar code in optimade-python-tools

https://github.com/Materials-Consortia/optimade-python-tools/blob/281ca780881d9529d7d247e5075eddf08152a362/optimade/server/main.py#L57-L59

they don't add the full path to the corresponding arguments.

I changed the code to be similar as optimade-python-tools and now everything seems to work. I removed the `get_custom_base_url_path()` function for maintainability, as it remains unused now.

2022-06-01 13:33 UTC, unkcpz approved these changes
@eimrek thanks. It looks all good to me.

2022-06-01 13:34 UTC, unkcpz commented
Hi @CasperWA, since this is not a big PR and a quick fix of things that bring issues to materials cloud page. I will do the merge without your approval, hope you don't mind.

2022-06-01 14:56 UTC, unkcpz requested changes
@eimrek make a test on materials cloud and still not working.

2022-06-01 16:39 UTC, eimrek commented
Important to use `root_path` in the config file.

Everything works well on materialscloud, if `base_url` is just the domain and `root_path` is the rest before the optimade-specific part. E.g.

```
  "base_url": "https://dev-aiida.materialscloud.org",
  "root_path": "/optimade-sample/optimade",
```

2022-06-02 07:48 UTC, unkcpz commented on aiida_optimade/main.py
> +    root_path=CONFIG.root_path,
I think we'd remove this it should read from `CONFIG` or we also explicitly set `base_url`.

2022-06-02 09:38 UTC, eimrek commented on aiida_optimade/main.py
> +    root_path=CONFIG.root_path,
removing `root_path` didn't work. So i added also `base_url` to be consistent

2022-06-02 10:46 UTC, unkcpz approved these changes
It is tested and works fine on Materials cloud

2022-06-02 10:56 UTC, merged