Drop py38
aiidateam/aiida-optimade pull request #500
Opened 2023-11-02 11:25 UTC by eimrek

fixes #499

2023-11-02 11:36 UTC, eimrek commented
@CasperWA I also added 3.11 to the CI tests. i guess if they pass, I can add that to the list of supported python versions as well. Then the versions match with aiida-core.

2023-11-02 11:41 UTC, eimrek commented
@CasperWA regarding the readme compatilibty matrix, we still keep versions 1.0-1.2 compatible with AiiDA 2.0-3.0, right? It should be the case, as long as you use the don't use python 3.8.

2023-11-06 10:37 UTC, CasperWA requested changes
Looks good to me.

Did you run `pyupgrade --py39-plus` on all the files or where do the other changes come from (related to `open()` and such)?

2023-11-06 10:37 UTC, CasperWA commented on README.md
> +| `v1.2 < v2.0` | ![Compatibility for v1.0][AiiDA v2 range] |  [![PyPI pyversions](https://img.shields.io/pypi/pyversions/aiida-optimade)](https://pypi.org/project/aiida-optimade) | ![OPTIMADE API co
I suppose the AiiDA range here should be updated?

2023-11-06 10:38 UTC, CasperWA commented
> @CasperWA regarding the readme compatilibty matrix, we still keep versions 1.0-1.2 compatible with AiiDA 2.0-3.0, right? It should be the case, as long as you use the don't use python 3.8.

Hmm. I'd only keep it compatible with the versions of AiiDA that support Python 3.8, I suppose?

2023-11-06 10:39 UTC, CasperWA commented on README.md
> +| `v1.2 < v2.0` | ![Compatibility for v1.0][AiiDA v2 range] |  [![PyPI pyversions](https://img.shields.io/pypi/pyversions/aiida-optimade)](https://pypi.org/project/aiida-optimade) | ![OPTIMADE API co
Ah - maybe it should indeed be changed in the line below as I also suggest [here](https://github.com/aiidateam/aiida-optimade/pull/500#issuecomment-1794529906).

2023-11-06 12:04 UTC, eimrek commented
thanks @CasperWA 

> Did you run pyupgrade --py39-plus on all the files or where do the other changes come from (related to open() and such)?

I ran `pyupgrade --py37-plus` before (that changed open()) but now also `pyupgrade --py39-plus`, which introduced many changes to the typing library imports.

Regarding the compatilibity matrix, i updated according to the following:
* aiida >=2.0.0, <2.4.0 is compatible with py3.8, so i used that range for 1.0-1.2
* aiida >=2.2.0 is compatible with py 3.11, so i used that for the new version that will also be compatible with py3.11.

Feel free to suggest alternatives.

2023-11-06 12:22 UTC, CasperWA approved these changes
This looks good to me.

After merging this, the currently failing dependabot PRs should be updated and hopefully they will succeed - then they should be merged and v1.2.0 should be released (probably after running CI workflows to check for any new dependency updates).

Note, the dependabot PRs should auto-update, if not, one should wait until the CI workflows running after merging this PR finish and then the PRs should be updated manually.

2023-11-06 12:32 UTC, merged

2023-11-06 14:03 UTC, eimrek commented
thanks @CasperWA the PRs didnt seem to get updated automatically. I merged develop into the aiida update PR #484. Is this what you meant? If that's fine i'll do the same for #482 as well.

2023-11-06 14:45 UTC, CasperWA commented
So I'll just finish up with merging the latest dependency updates, and then I'll release v1.2.0. Please then check everything you need is solved by v1.2.0 concerning the immediate issue(s) and subsequent requirement for dropping Python 3.8 support :)

2023-11-07 10:32 UTC, eimrek commented
thanks @CasperWA! Everything works great!

2023-11-07 12:49 UTC, CasperWA commented
> thanks @CasperWA! Everything works great!

Thank you! 😄